### PR TITLE
Add types for helmet.contentSecurityPolicy

### PR DESCRIPTION
**Pull request by bconnorwhite**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)
      
Adding types for https://github.com/fastify/fastify-helmet/pull/109

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you add an unit test for the typing?

**Comment by bconnorwhite** [comment]
Sure @climba03003, added

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — APPROVED** [review]
LGTM.

**Pull request merged**
