### PR TITLE
types: export FastifyHelmetOptions to TypeScript users

### PR DESCRIPTION
**Pull request by sniperwolf**
#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by darkgl0w — COMMENTED** [review]
Thank you for your contribution ^_^
Can you please add a test inside the `index.test-d.ts` file ?

**Comment by sniperwolf** [comment]
@darkgl0w Something like the following make sense as a test to prove that `fastify-helmet` instance is using the 
`FastifyHelmetOptions` options?

```ts
expectType<FastifyPluginCallback<FastifyHelmetOptions> & {
    contentSecurityPolicy: typeof helmet.contentSecurityPolicy;
}>(fastifyHelmet);
```

**Comment by darkgl0w** [comment]
Yes something like this should be enough.

As we export `FastifyHelmetOptions` we can do something like this too :
```ts
const helmetOptions = {
  contentSecurityPolicy: false,
  dnsPrefetchControl: false,
  expectCt: false,
  frameguard: false,
  hidePoweredBy: false,
  hsts: false,
  ieNoOpen: false,
  noSniff: false,
  permittedCrossDomainPolicies: false,
  referrerPolicy: false,
  xssFilter: false
}

// or maybe: expectAssignable<FastifyHelmetOptions>(helmetOptions);
expectType<FastifyHelmetOptions>(helmetOptions);
```

**Review by mcollina — COMMENTED** [review]
Can you please add a unit test?

**Review by darkgl0w — APPROVED** [review]
LGTM

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
