### PR TITLE
fix: checks if the `helmet` decorator exists before decorating `reply`

### PR DESCRIPTION
**Pull request by darkgl0w**
Hello.

This PR aims to :
- checks if the `helmet` decorator exists before decorating `reply` (cf.: https://github.com/fastify/fastify-helmet/pull/166#issuecomment-1014531598)

#### Checklist

- [x] run `npm run test` ~~and `npm run benchmark`~~
- [x] tests ~~and/or benchmarks~~ are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Fdawgs — APPROVED** [review]

**Comment by Fdawgs** [comment]
Seems this was masking another issue 😢: https://github.com/fastify/fastify-helmet/issues/168

**Comment by climba03003** [comment]
> Seems this was masking another issue 😢: #168

`fastify.addHook('onRequest')` and `fastify.addHook('onRoute')` behavior pretty differently.
The previous one exist no matter the route specified or not. The latter one only exist for registered route.

I think that is the problem.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Fdawgs** [comment]
> > Seems this was masking another issue 😢: #168
> 
> `fastify.addHook('onRequest')` and `fastify.addHook('onRoute')` behavior pretty differently. The previous one exist no matter the route specified or not. The latter one only exist for registered route.
> 
> Also, the `onRequest` hook run order is not guarantee to respect the plugin register order from the current code.

Cheers @climba03003, that makes sense.

**Review by climba03003 — APPROVED** [review]

**Pull request merged**
