### PR TITLE
Uses import = require to import helmet types

### PR DESCRIPTION
**Pull request by fox1t**
Fixes https://github.com/fastify/fastify-helmet/pull/95#issuecomment-692415769

Since helmet is using `export =` the only way to make it work reliably with `esModuleInterop: true AND false` is to use `import = require`. This kind of import will tell TS that we are importing a `module.exports` namespace that could be callable:  in fact now TS follows the ESM spec and makes namespaces non-callable by default.

Side note: we need to test our typings, for all our plugins and fastify itself, against all possible combinations of TS configurations to prevent these issues in the future.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by kibertoad — APPROVED** [review]

**Review by zekth — APPROVED** [review]

**Comment by gtolarc** [comment]
v5.0.2 certainly does not work in projects with esModuleInterop: true. So it'd better release this on npm as soon as possible:) @mcollina

**Comment by fox1t** [comment]
@gtolarc I am going to realease the patch.

**Comment by fox1t** [comment]
v5.0.3 Released

**Pull request merged**
