### PR TITLE
fix: update type definitions

### PR DESCRIPTION
**Pull request by gperdomor**
HelmetOptions is not exported from helmet anymore

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by fox1t — CHANGES_REQUESTED** [review]
Would you mind to update this package typings to match this one? https://github.com/fastify/fastify-swagger/blob/master/index.d.ts

Basically use default + named exports in the place of namespace export.

**Comment by gperdomor** [comment]
@fox1t I have problems with HelmetOptions with is not exported [anymore](https://github.com/helmetjs/helmet/blob/master/CHANGELOG.md), so I'm trying to do this but still fails...

```
import "fastify";
import { FastifyPlugin } from "fastify";
import * as helmet from "helmet";

type FastifyHelmetOptions = Parameters<typeof helmet>[0]; <--------- THIS

export const fastifyHelmet: FastifyPlugin<FastifyHelmetOptions>;

export default fastifyHelmet;
```

**Comment by fox1t** [comment]
@gperdomor [helmet](https://github.com/helmetjs/helmet) doesn't provide types itself. That code will never work since TS isn't importing any types.

**Comment by gperdomor** [comment]
> @gperdomor [helmet](https://github.com/helmetjs/helmet) doesn't provide types itself. That code will never work since TS isn't importing any types.

tthat is the proposed solution in helmet's changelog 😕 ... What you propose?

**Comment by fox1t** [comment]
I've fixed your PR. Sorry for editing it like this, but this was a really weird TS issue.

**Review by fox1t — APPROVED** [review]
LGTM

**Comment by gperdomor** [comment]
@fox1t don't worry, thx 😄

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
