### PR TITLE
ci: only trigger on pushes to main branches

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/fastify/workflows/issues/56. 

This will stop PRs from running the CI workflows twice (one for the PR and one for the push to the PR), which will cut down run times for Dependabot PRs that wait for both to complete before merging, and the time waiting for all checks to complete for normal PRs (see https://github.com/fastify/fastify-helmet/pull/195/checks).

If happy with this then i will apply to rest of the repos.

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — APPROVED** [review]

**Review by climba03003 — CHANGES_REQUESTED** [review]
How about version branches?

The trigger is the limitation of Github itself and I would accept the current state.
It is actually cause only when you have access to the repo.

If someone really don't want to trigger the `push` event, you can actually `Fork and PR`.

**Comment by Fdawgs** [comment]
> How about version branches?

Could add something like `- 'v*'`?

**Comment by Eomm** [comment]
> Could add something like - 'v*'?

Yes, we always use that pattern.

Maybe just `v[0-9.-]{1,8}` if we want to be stricter

**Comment by Fdawgs** [comment]
> > Could add something like - 'v*'?
> 
> Yes, we always use that pattern.
> 
> Maybe just `v[0-9.-]{1,8}` if we want to be stricter

Doesn't [appear to like the curly braces](https://github.com/fastify/fastify-helmet/actions/runs/2880984357), and it's not one of the [allowed values in filter list](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).

An alternative would be `v[0-9]+.[0-9]+.[0-9]+`.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
Just nagging here:
What if somebody wants to do a -rc1  suffix?

**Comment by Fdawgs** [comment]
> Just nagging here: What if somebody wants to do a -rc1 suffix?

Sorted, just using 'v*' now.

**Review by Uzlopak — APPROVED** [review]
LGTM

Worst case scenaria if somebody creates a branch "very-good" is that the pipeline runs twice. I think this is acceptable.

**Review by climba03003 — COMMENTED** [review]
I am not sure if it worth.
The `push` CI is run on the branch and the `pull request` CI is run on pull request.
Which means, every new branch will not be run if it does not send PR.

No, CI test on feature branch.

I am not blocked to land this, it just worth it or not. Will someone actually use `feature-branch` and check CI?

**Review by Eomm — APPROVED** [review]
I think it worth trying this configuration.

We don't push code into the repo without PR, except the bump version one, so I don't see blockers here.

What I like most about this PR (if it works) is that we don't waste resources (electricity, logs, disk, network)

Merging

**Comment by Fdawgs** [comment]
What's been the general consensus on this? Worth adding to other repos?

**Pull request merged**
